//
//  ColourNames.swift
//  Fask
//
//  Created by Simon Colton on 12/09/2015.
//  Copyright (c) 2018 ThoseMetamakers. All rights reserved.
//

import Foundation

enum ColourNames: Int{
    
    case indianRed = 0
    case lightCoral
    case salmon
    case darkSalmon
    case lightSalmon
    case crimson
    case red
    case fireBrick
    case darkRed
    case pink
    case lightPink
    case hotPink
    case deepPink
    case mediumVioletRed
    case paleVioletRed
    case coral
    case tomato
    case orangeRed
    case darkOrange
    case orange
    case gold
    case yellow
    case lightYellow
    case lemonChiffon
    case lightGoldenrodYellow
    case papayaWhip
    case moccasin
    case peachPuff
    case paleGoldenrod
    case khaki
    case darkKhaki
    case lavender
    case thistle
    case plum
    case violet
    case orchid
    case fuchsia
    case magenta
    case mediumOrchid
    case mediumPurple
    case amethyst
    case blueViolet
    case darkViolet
    case darkOrchid
    case darkMagenta
    case purple
    case indigo
    case slateBlue
    case darkSlateBlue
    case greenYellow
    case chartreuse
    case lawnGreen
    case lime
    case limeGreen
    case paleGreen
    case lightGreen
    case mediumSpringGreen
    case springGreen
    case mediumSeaGreen
    case seaGreen
    case forestGreen
    case green
    case darkGreen
    case yellowGreen
    case oliveDrab
    case olive
    case darkOliveGreen
    case mediumAquamarine
    case darkSeaGreen
    case lightSeaGreen
    case darkCyan
    case teal
    case aqua
    case cyan
    case lightCyan
    case paleTurquoise
    case aquamarine
    case turquoise
    case mediumTurquoise
    case darkTurquoise
    case cadetBlue
    case steelBlue
    case lightSteelBlue
    case powderBlue
    case lightBlue
    case skyBlue
    case lightSkyBlue
    case deepSkyBlue
    case dodgerBlue
    case cornflowerBlue
    case mediumSlateBlue
    case royalBlue
    case blue
    case mediumBlue
    case darkBlue
    case navy
    case midnightBlue
    case cornsilk
    case blanchedAlmond
    case bisque
    case navajoWhite
    case wheat
    case burlyWood
    case tan
    case rosyBrown
    case sandyBrown
    case goldenrod
    case darkGoldenrod
    case peru
    case chocolate
    case saddleBrown
    case sienna
    case brown
    case maroon
    case white
    case snow
    case honeydew
    case mintCream
    case azure
    case aliceBlue
    case ghostWhite
    case whiteSmoke
    case seashell
    case beige
    case oldLace
    case floralWhite
    case ivory
    case antiqueWhite
    case linen
    case lavenderBlush
    case mistyRose
    case gainsboro
    case lightGray
    case silver
    case darkGray
    case gray
    case dimGray
    case lightSlateGray
    case slateGray
    case darkSlateGray
    case black
    case transparent
    
}
